export type ToolCategoryKey =
  | "date-time"
  | "dev"
  | "finance"
  | "web3"
  | "mini"
  | "image-file"
  | "ai";

export type ToolStatus = "ready" | "planned";

export type ToolDefinition = {
  slug: string;
  name: string;
  summary: string;
  category: ToolCategoryKey;
  targetKeyword: string;
  status: ToolStatus;
};

export type ToolCategory = {
  key: ToolCategoryKey;
  title: string;
  description: string;
};

type SummaryLocale = "en" | "zh";

const CATEGORY_META: ToolCategory[] = [
  {
    key: "web3",
    title: "Web3",
    description: "EVM, Bitcoin, PSBT, and on-chain analysis tools.",
  },
  {
    key: "ai",
    title: "AI Light Tools",
    description: "Prompt and content formatting helpers.",
  },
  {
    key: "date-time",
    title: "Date / Time",
    description: "Timestamp, timezone, duration, and calendar utilities.",
  },
  {
    key: "dev",
    title: "Dev / Encoding",
    description: "JSON, text, encoding, and debugging helpers.",
  },
  {
    key: "finance",
    title: "Finance",
    description: "Interest, ROI, tax, and portfolio math tools.",
  },
  {
    key: "mini",
    title: "Mini / Fun",
    description: "Quick tests, generators, and lightweight utilities.",
  },
  {
    key: "image-file",
    title: "Image / File",
    description: "Image, PDF, and file conversion helpers.",
  },
];

function titleFromSlug(slug: string) {
  return slug
    .split("-")
    .map((part) => {
      if (part === "json" || part === "yaml" || part === "xml" || part === "url" || part === "jwt") {
        return part.toUpperCase();
      }
      if (part === "btc" || part === "evm" || part === "psbt" || part === "pdf" || part === "jpg" || part === "png" || part === "md5" || part === "sha256" || part === "roi" || part === "vat" || part === "ai") {
        return part.toUpperCase();
      }
      return part.charAt(0).toUpperCase() + part.slice(1);
    })
    .join(" ");
}

const SUMMARY_OVERRIDES_EN: Record<string, string> = {
  "timestamp-converter": "Convert Unix timestamps into readable UTC, local time, and ISO dates.",
  "current-timestamp": "Get the current Unix timestamp in seconds and milliseconds instantly.",
  "timestamp-milliseconds-converter": "Switch between 10-digit seconds timestamps and 13-digit milliseconds.",
  "date-difference-calculator": "Calculate the exact gap between two dates in days, hours, minutes, and seconds.",
  "time-difference-calculator": "Measure the difference between two times, including overnight spans.",
  "add-time-to-date": "Add days, hours, and minutes to a base date and preview the result.",
  "subtract-time-from-date": "Subtract days, hours, and minutes from a base date and preview the result.",
  "business-days-calculator": "Count business days between two dates and separate weekends.",
  "working-days-exclude-weekends": "Add working days to a start date while skipping weekends.",
  "age-calculator-exact": "Calculate exact age in years, months, and days from any birth date.",
  "countdown-timer-date": "Count down live to a target date and time in the browser.",
  "timezone-converter": "Convert a date and time from one timezone to another with UTC output.",
  "timezone-difference-calculator": "Compare two timezones and inspect their current offsets and local times.",
  "date-to-week-number": "Convert a date into its ISO week number and week year.",
  "date-format-converter": "Turn one date input into ISO, UTC, local, and common calendar formats.",
  "date-string-parser": "Parse a human-readable date string into UTC, ISO, local time, and timestamp.",
  "time-duration-calculator": "Convert a duration into total seconds, minutes, hours, and milliseconds.",
  "day-of-year-calculator": "Find the day number within the year and how many days remain.",
  "leap-year-checker": "Check whether a year is a leap year and see the matching rule.",
  "json-formatter": "Format and pretty-print JSON with indentation for easier reading.",
  "json-minifier": "Minify JSON by removing whitespace and compressing it into one line.",
  "json-validator": "Validate JSON input and show whether the structure is valid.",
  "json-escape-unescape": "Escape JSON string content or unescape it back into readable text.",
  "base64-encode-decode": "Encode text to Base64 or decode Base64 back into readable text.",
  "binary-to-text": "Decode 8-bit binary bytes into readable UTF-8 text instantly.",
  "text-to-binary": "Convert plain text into 8-bit binary bytes for quick inspection.",
  "url-encode-decode": "Encode or decode URL components for query strings and safe links.",
  "uuid-generator": "Generate one or more UUID v4 values instantly in the browser.",
  "word-character-counter": "Count words, characters, lines, and paragraphs in a block of text.",
  "text-case-converter": "Convert text between lower, upper, title, sentence, and slug-style cases.",
  "slug-generator": "Turn text into a clean URL-friendly slug instantly.",
  "duplicate-line-remover": "Remove duplicate lines while preserving the first occurrence.",
  "line-sorter": "Sort lines alphabetically with direction and whitespace controls.",
  "random-string-generator": "Generate random strings with configurable length and character sets.",
  "unicode-converter": "Convert text into Unicode code points or decode Unicode escapes back to text.",
  "text-diff-checker": "Compare two text blocks line by line and inspect added or removed lines.",
  "regex-tester": "Test a regular expression against text and inspect matches instantly.",
  "regex-replace-tool": "Run regex-based find and replace in the browser with instant output.",
  "hash-generator-md5-sha256": "Generate MD5 and SHA-256 hashes for any text input instantly.",
  "hex-to-string-converter": "Decode hexadecimal bytes into readable UTF-8 text instantly.",
  "string-to-hex-converter": "Convert plain text into hexadecimal bytes for debugging or encoding checks.",
  "jwt-decoder": "Decode JWT header and payload values instantly in the browser.",
  "json-flatten-tool": "Flatten nested JSON objects into dot-path key/value pairs.",
  "json-diff-viewer": "Compare two JSON documents and inspect added, removed, or changed paths.",
  "json-to-csv-converter": "Convert JSON arrays or objects into CSV rows instantly.",
  "csv-to-json-converter": "Convert CSV data with headers into structured JSON instantly.",
  "xml-to-json-converter": "Convert XML nodes and attributes into readable JSON.",
  "yaml-to-json-converter": "Convert common YAML objects and lists into JSON instantly.",
  "percentage-calculator": "Calculate percentages, percent-of-total values, and reverse percentage totals.",
  "discount-calculator": "Calculate discount savings and final sale price instantly.",
  "profit-loss-calculator": "Calculate profit or loss amounts and percentage margin from buy and sell prices.",
  "roi-calculator": "Calculate return on investment and net profit from cost and return values.",
  "compound-interest-calculator": "Estimate compound growth with recurring monthly contributions.",
  "dca-investment-calculator": "Calculate average cost, units accumulated, and current value from recurring buys.",
  "simple-interest-calculator": "Calculate simple interest and total repayment from principal, rate, and time.",
  "loan-payment-calculator": "Estimate monthly loan payments, total paid, and total interest.",
  "mortgage-calculator": "Estimate mortgage monthly payments, loan principal, and total interest.",
  "tax-calculator": "Calculate tax amount and total price from a pre-tax value and rate.",
  "vat-calculator": "Calculate VAT amount and gross total from a net amount instantly.",
  "currency-converter": "Convert between two currencies with a custom exchange rate input.",
  "exchange-rate-history-viewer": "Inspect a manual exchange-rate history series with change, high, low, and average values.",
  "inflation-calculator": "Adjust a present amount by inflation and compare future purchasing power.",
  "savings-growth-calculator": "Project long-term savings growth with monthly contributions and return assumptions.",
  "net-profit-margin-calculator": "Calculate net profit and net profit margin from revenue and expenses.",
  "break-even-calculator": "Calculate break-even units and revenue from fixed and variable costs.",
  "stock-average-price-calculator": "Calculate stock average cost basis, total shares, and unrealized profit or loss.",
  "evm-address-checker": "Validate Ethereum and EVM addresses, including checksum formatting.",
  "evm-checksum-converter": "Convert an EVM address into its EIP-55 checksum format instantly.",
  "token-decimals-converter": "Convert token display amounts to raw integer units using token decimals.",
  "wei-eth-converter": "Convert between wei, gwei, and ETH amounts instantly.",
  "gas-fee-calculator": "Calculate total gas cost from gas limit and gas price inputs.",
  "transaction-decoder": "Decode raw signed EVM transactions into readable fields instantly.",
  "calldata-decoder": "Decode EVM calldata using a provided function fragment.",
  "event-log-decoder": "Decode EVM event logs from topics and data using an event fragment.",
  "abi-encode-tool": "ABI-encode Solidity types and values into a hex payload instantly.",
  "abi-decode-tool": "ABI-decode hex data into typed Solidity values in the browser.",
  "keccak256-hash-generator": "Generate Keccak-256 hashes for text or hex input in the browser.",
  "signature-verifier": "Verify whether a signed message matches an expected EVM address.",
  "recover-address-from-signature": "Recover the signer address from a message and EVM signature.",
  "contract-bytecode-analyzer": "Inspect contract bytecode size, metadata hints, and EIP-170 usage.",
  "btc-address-generator": "Generate a random Bitcoin address with common address formats in the browser.",
  "btc-address-validator": "Validate Bitcoin base58 and bech32 addresses in the browser.",
  "batch-btc-address-generator": "Generate a batch of random Bitcoin addresses for quick testing or fixtures.",
  "btc-transaction-decoder": "Decode raw Bitcoin transactions into summary fields instantly.",
  "btc-raw-transaction-parser": "Parse Bitcoin raw transactions into detailed input and output data.",
  "btc-fee-calculator": "Calculate Bitcoin transaction fees and fee rates from inputs and outputs.",
  "btc-fee-estimator": "Estimate Bitcoin fees from virtual size and a target sat/vB rate.",
  "btc-satoshi-converter": "Convert between BTC amounts and satoshis instantly.",
  "btc-script-decoder": "Decode Bitcoin script hex into ASM opcodes and data pushes.",
  "btc-transaction-size-calculator": "Estimate Bitcoin transaction size, vbytes, and weight units.",
  "btc-change-output-calculator": "Calculate Bitcoin change output values from inputs, send amount, and fees.",
  "btc-dust-limit-calculator": "Estimate Bitcoin dust thresholds for common output types.",
  "btc-locktime-calculator": "Convert and inspect Bitcoin nLockTime values as heights or timestamps.",
  "btc-weight-calculator": "Estimate Bitcoin transaction weight units, witness bytes, and virtual size.",
  "psbt-builder": "Build a simple Bitcoin PSBT from input, recipient, and optional change details.",
  "psbt-decoder": "Decode a Bitcoin PSBT into readable inputs, outputs, and signing fields.",
  "psbt-analyzer": "Analyze PSBT signing completeness, UTXO coverage, and visible fee data.",
  "ordinal-inscription-builder": "Build a simple Ordinals inscription manifest and content preview in the browser.",
  "ordinal-fee-estimator": "Estimate commit and reveal fees for a simple Ordinals inscription flow.",
  "nonce-checker": "Check latest and pending EVM account nonce values from a live RPC endpoint.",
  "ordinal-size-calculator": "Estimate reveal size, script bytes, and chunk count for Ordinals content.",
  "transaction-analyzer": "Analyze a raw signed EVM transaction and summarize gas, bytes, and signature data.",
  "multi-chain-tx-viewer": "Query the same EVM transaction hash across multiple preset chains.",
  "price-impact-calculator": "Estimate AMM swap price impact from reserves, trade size, and fee bps.",
  "slippage-calculator": "Calculate minimum received and actual slippage against a chosen tolerance.",
  "arbitrage-profit-calculator": "Estimate cross-venue arbitrage profit after fees, slippage, and transfer costs.",
  "oracle-delay-analyzer": "Measure oracle update lag against a reference timestamp and heartbeat.",
  "gas-optimization-analyzer": "Estimate calldata gas overhead and fee savings from a possible gas reduction.",
  "liquidation-risk-calculator": "Estimate collateral LTV, liquidation price, and remaining buffer.",
  "prompt-formatter": "Clean up prompt structure, spacing, and inline sections for reuse.",
  "prompt-template-generator": "Generate reusable prompt templates for writing, coding, or research tasks.",
  "text-to-markdown": "Turn plain text notes into a simple markdown structure instantly.",
  "markdown-preview": "Preview markdown with headings, lists, and inline formatting in the browser.",
  "json-to-prompt": "Turn structured JSON fields into a readable prompt template.",
  "code-explainer-lite": "Explain code structure with a lightweight browser-side summary.",
  "text-summarizer-lite": "Create a short summary from a longer text block with a simple heuristic.",
  "keyword-extractor": "Extract repeated keyword candidates from a text block quickly.",
  "ai-token-estimator": "Estimate prompt token usage from text length with a fast rough heuristic.",
  "chat-format-converter": "Convert raw conversation text into chat-role lines or bullet notes.",
  "random-decision-maker": "Pick one option at random from a custom list instantly.",
  "random-number-generator": "Generate random integers or decimals within a chosen range.",
  "random-password-generator": "Generate random passwords with adjustable length and symbol options.",
  "random-color-generator": "Generate random hex colors and preview a quick palette.",
  "random-gradient-generator": "Generate random CSS linear gradients with instant preview output.",
  "coin-flip-simulator": "Flip a virtual coin and track heads or tails results instantly.",
  "dice-roll-simulator": "Roll one or more virtual dice and see the total immediately.",
  "number-guessing-game": "Play a browser number guessing game with attempt tracking.",
  "click-speed-test": "Measure how many clicks you can make in a short timed test.",
  "reaction-time-test": "Test your visual reaction speed by clicking as soon as the panel changes.",
  "typing-speed-test": "Measure typing speed, accuracy, and completion time in the browser.",
  "memory-game": "Play a simple card matching memory game with move counting.",
  "2048-game": "Play a browser version of 2048 and merge tiles toward the winning block.",
  "sudoku-generator": "Generate a browser sudoku puzzle with editable cells and answer checking.",
  "spin-wheel-picker": "Pick a random option from a custom list with a wheel-style chooser.",
  "jpg-to-png": "Convert a JPG image into PNG format directly in the browser.",
  "image-to-base64": "Convert an uploaded image into a Base64 data URL instantly.",
  "base64-to-image": "Decode a Base64 image string and preview it in the browser.",
  "pdf-to-image": "Render a PDF page into a downloadable PNG preview in the browser.",
  "image-to-pdf": "Combine one or more JPG or PNG images into a downloadable PDF file.",
  "pdf-merge-tool": "Merge multiple PDF files into a single PDF in browser order.",
  "pdf-split-tool": "Split a PDF by page ranges or export every page as separate files.",
  "pdf-compress-tool": "Run a lightweight browser-side PDF optimization pass and compare file size.",
  "file-size-converter": "Convert file sizes across bytes, KB, MB, GB, and TB.",
  "unit-converter-bytes": "Convert raw byte values into decimal and binary storage units.",
};

const SUMMARY_OVERRIDES_ZH: Record<string, string> = {
  "timestamp-converter": "把 Unix 时间戳转换为 UTC、本地时间和 ISO 日期。",
  "current-timestamp": "即时获取当前 Unix 秒级和毫秒级时间戳。",
  "timestamp-milliseconds-converter": "在 10 位秒级时间戳和 13 位毫秒时间戳之间快速切换。",
  "date-difference-calculator": "计算两个日期之间精确相差多少天、小时、分钟和秒。",
  "time-difference-calculator": "计算两个时刻之间的差值，并支持跨天场景。",
  "add-time-to-date": "给基础日期增加天、小时和分钟并查看结果。",
  "subtract-time-from-date": "从基础日期中减去天、小时和分钟并查看结果。",
  "business-days-calculator": "统计两个日期之间的工作日数量并区分周末天数。",
  "working-days-exclude-weekends": "在排除周末的前提下，把工作日数量加到开始日期上。",
  "age-calculator-exact": "根据出生日期计算精确到年、月、日的年龄。",
  "countdown-timer-date": "对目标日期时间做实时倒计时并持续更新。",
  "timezone-converter": "把一个时区下的日期时间换算到另一个时区。",
  "timezone-difference-calculator": "比较两个时区的当前偏移和本地时间差异。",
  "date-to-week-number": "把一个日期转换为 ISO 周数和所属周年份。",
  "date-format-converter": "把同一个日期输入转换为 ISO、UTC、本地时间和常见格式。",
  "date-string-parser": "把可读日期字符串解析为 UTC、ISO、本地时间和时间戳。",
  "time-duration-calculator": "把时长换算为总秒数、总分钟数、总小时数和毫秒数。",
  "day-of-year-calculator": "计算某一天是一年中的第几天以及剩余天数。",
  "leap-year-checker": "判断某一年是否为闰年，并展示判定规则。",
  "json-formatter": "格式化并美化 JSON，方便阅读和调试。",
  "json-minifier": "压缩 JSON，移除空白并输出单行结果。",
  "json-validator": "校验 JSON 输入是否合法，并显示解析结果。",
  "json-escape-unescape": "对 JSON 字符串内容做转义或反向还原。",
  "base64-encode-decode": "把文本编码为 Base64，或把 Base64 解码回可读内容。",
  "binary-to-text": "把 8 位二进制字节快速解码为可读 UTF-8 文本。",
  "text-to-binary": "把普通文本转换为 8 位二进制字节，便于查看编码结果。",
  "url-encode-decode": "对 URL 组件进行编码或解码，便于处理参数和链接。",
  "uuid-generator": "在浏览器中即时生成一个或多个 UUID v4。",
  "word-character-counter": "统计文本中的单词数、字符数、行数和段落数。",
  "text-case-converter": "在小写、大写、标题式、句式和 slug 风格之间转换文本。",
  "slug-generator": "把文本快速转换为适合 URL 的 slug。",
  "duplicate-line-remover": "删除重复行，并保留每个内容首次出现的位置。",
  "line-sorter": "按字母顺序对文本行排序，并支持方向与空白控制。",
  "random-string-generator": "按指定长度和字符集生成随机字符串。",
  "unicode-converter": "把文本转成 Unicode 编码点，或把 Unicode 转义还原成文本。",
  "text-diff-checker": "逐行比较两段文本，并查看新增和删除的行。",
  "regex-tester": "测试正则表达式并即时查看匹配结果。",
  "regex-replace-tool": "在浏览器里做基于正则的查找替换，并即时输出结果。",
  "hash-generator-md5-sha256": "即时生成任意文本的 MD5 和 SHA-256 哈希值。",
  "hex-to-string-converter": "把十六进制字节即时解码为可读 UTF-8 文本。",
  "string-to-hex-converter": "把普通文本转换为十六进制字节，便于调试和编码检查。",
  "jwt-decoder": "在浏览器中即时解码 JWT 的 header 和 payload。",
  "json-flatten-tool": "把嵌套 JSON 扁平化为点路径键值对。",
  "json-diff-viewer": "比较两份 JSON，并查看新增、删除或变化的路径。",
  "json-to-csv-converter": "把 JSON 数组或对象即时转换为 CSV 行数据。",
  "csv-to-json-converter": "把带表头的 CSV 数据即时转换为结构化 JSON。",
  "xml-to-json-converter": "把 XML 节点和属性转换为可读 JSON。",
  "yaml-to-json-converter": "把常见 YAML 对象和列表即时转换为 JSON。",
  "percentage-calculator": "计算百分比、总量占比结果，以及反推总量。",
  "discount-calculator": "即时计算折扣金额和最终到手价。",
  "profit-loss-calculator": "根据买入价、卖出价和数量计算盈亏金额与比例。",
  "roi-calculator": "根据成本和回报价值计算 ROI 与净收益。",
  "compound-interest-calculator": "估算带每月追加投入的复利增长结果。",
  "dca-investment-calculator": "根据多次定投价格计算平均成本、累计数量和当前市值。",
  "simple-interest-calculator": "根据本金、利率和时间计算单利与总金额。",
  "loan-payment-calculator": "估算贷款月供、总支付金额和总利息。",
  "mortgage-calculator": "估算房贷月供、贷款本金和总利息。",
  "tax-calculator": "根据税前金额和税率计算税额与含税总价。",
  "vat-calculator": "根据净额即时计算 VAT 税额与含税总额。",
  "currency-converter": "根据自定义汇率在两种货币之间进行换算。",
  "exchange-rate-history-viewer": "分析手动输入的历史汇率序列，查看涨跌、均值、高低点。",
  "inflation-calculator": "按通胀率换算未来成本并比较购买力变化。",
  "savings-growth-calculator": "结合每月投入和收益率预测长期储蓄增长。",
  "net-profit-margin-calculator": "根据营收和支出计算净利润与净利率。",
  "break-even-calculator": "根据固定成本和单位成本结构计算盈亏平衡点。",
  "stock-average-price-calculator": "根据多笔买入批次计算股票平均成本、总股数和浮动盈亏。",
  "evm-address-checker": "校验 Ethereum / EVM 地址格式以及 checksum 是否正确。",
  "evm-checksum-converter": "把 EVM 地址即时转换为 EIP-55 checksum 格式。",
  "token-decimals-converter": "根据 token decimals 在显示金额和链上原始整数值之间转换。",
  "wei-eth-converter": "在 wei、gwei 和 ETH 之间即时换算金额。",
  "gas-fee-calculator": "根据 gas limit 和 gas price 即时计算总手续费。",
  "transaction-decoder": "把原始签名 EVM 交易即时解码为可读字段。",
  "calldata-decoder": "根据提供的函数片段解码 EVM calldata。",
  "event-log-decoder": "根据事件片段、topics 和 data 解码 EVM 日志。",
  "abi-encode-tool": "把 Solidity 类型和值即时 ABI 编码为 hex 结果。",
  "abi-decode-tool": "在浏览器中把 ABI 编码的 hex 数据解码为 Solidity 值。",
  "keccak256-hash-generator": "在浏览器中对文本或 hex 输入生成 Keccak-256 哈希。",
  "signature-verifier": "验证消息签名是否匹配预期的 EVM 地址。",
  "recover-address-from-signature": "根据消息和 EVM 签名恢复出签名地址。",
  "contract-bytecode-analyzer": "分析合约字节码大小、metadata 特征和 EIP-170 占用情况。",
  "btc-address-generator": "在浏览器中随机生成 Bitcoin 地址及常见地址格式。",
  "btc-address-validator": "在浏览器中校验 Bitcoin 的 base58 和 bech32 地址。",
  "batch-btc-address-generator": "批量生成随机 Bitcoin 地址，适合测试和样例数据。",
  "btc-transaction-decoder": "把原始 Bitcoin 交易即时解码为摘要字段。",
  "btc-raw-transaction-parser": "把 Bitcoin 原始交易解析为输入输出等详细结构。",
  "btc-fee-calculator": "根据输入输出总额计算 Bitcoin 手续费和费率。",
  "btc-fee-estimator": "根据虚拟大小和目标 sat/vB 费率估算 Bitcoin 手续费。",
  "btc-satoshi-converter": "在 BTC 金额和 satoshi 之间即时换算。",
  "btc-script-decoder": "把 Bitcoin 脚本 hex 解码为 ASM 操作码和数据片段。",
  "btc-transaction-size-calculator": "估算 Bitcoin 交易大小、vbytes 和权重单位。",
  "btc-change-output-calculator": "根据输入、收款金额和手续费计算 Bitcoin 找零输出。",
  "btc-dust-limit-calculator": "估算常见 Bitcoin 输出类型的 dust 阈值。",
  "btc-locktime-calculator": "把 Bitcoin nLockTime 在高度和时间戳语义之间转换和查看。",
  "btc-weight-calculator": "估算 Bitcoin 交易的权重单位、见证字节和虚拟大小。",
  "psbt-builder": "根据输入、收款和找零信息构建一个简单的 Bitcoin PSBT。",
  "psbt-decoder": "把 Bitcoin PSBT 解码为可读的输入、输出和签名字段。",
  "psbt-analyzer": "分析 PSBT 的签名完成度、UTXO 覆盖情况和可见手续费。",
  "ordinal-inscription-builder": "在浏览器中构建简单的 Ordinals 铭文清单和内容预览。",
  "ordinal-fee-estimator": "估算简单 Ordinals 铭文流程里的 commit 和 reveal 手续费。",
  "nonce-checker": "通过实时 RPC 节点查询 EVM 账户的 latest 和 pending nonce。",
  "ordinal-size-calculator": "估算 Ordinals 内容的 reveal 大小、脚本字节和分块数量。",
  "transaction-analyzer": "分析原始签名 EVM 交易，并汇总 gas、字节和签名信息。",
  "multi-chain-tx-viewer": "在多个预设 EVM 链上查询同一个交易哈希。",
  "price-impact-calculator": "根据储备、交易数量和手续费 bps 估算 AMM 价格影响。",
  "slippage-calculator": "计算最少收到数量，以及相对容忍度的实际滑点。",
  "arbitrage-profit-calculator": "在考虑手续费、滑点和转账成本后估算套利利润。",
  "oracle-delay-analyzer": "根据参考时间戳和 heartbeat 评估预言机更新延迟。",
  "gas-optimization-analyzer": "估算 calldata gas 开销，以及潜在优化后的手续费节省。",
  "liquidation-risk-calculator": "估算抵押仓位的 LTV、清算价格和剩余缓冲。",
  "prompt-formatter": "整理 prompt 的结构、空白和内联字段，方便复用。",
  "prompt-template-generator": "为写作、编码或研究任务生成可复用的 prompt 模板。",
  "text-to-markdown": "把纯文本笔记即时转换为简单的 Markdown 结构。",
  "markdown-preview": "在浏览器中预览带标题、列表和行内格式的 Markdown。",
  "json-to-prompt": "把结构化 JSON 字段转换为可读的 prompt 模板。",
  "code-explainer-lite": "在浏览器中用轻量规则总结代码结构和特征。",
  "text-summarizer-lite": "用简单规则把较长文本压缩为简短摘要。",
  "keyword-extractor": "快速提取文本中重复出现的关键词候选。",
  "ai-token-estimator": "基于文本长度快速粗略估算 prompt 的 token 数量。",
  "chat-format-converter": "把原始对话文本转换为 chat role 或要点列表格式。",
  "random-decision-maker": "从自定义选项列表中即时随机选出一个结果。",
  "random-number-generator": "在指定范围内生成随机整数或小数。",
  "random-password-generator": "按长度和符号选项即时生成随机密码。",
  "random-color-generator": "生成随机十六进制颜色并预览调色板。",
  "random-gradient-generator": "生成随机 CSS 线性渐变并即时预览。",
  "coin-flip-simulator": "模拟抛硬币并即时统计正反面结果。",
  "dice-roll-simulator": "模拟掷一个或多个骰子并查看总点数。",
  "number-guessing-game": "在浏览器里玩猜数字小游戏并记录尝试次数。",
  "click-speed-test": "测试短时间内的点击速度和每秒点击数。",
  "reaction-time-test": "在面板变色时立即点击，测试视觉反应速度。",
  "typing-speed-test": "在浏览器里测试打字速度、准确率和完成时间。",
  "memory-game": "玩一个简单的卡片配对记忆游戏并统计步数。",
  "2048-game": "在浏览器里玩 2048 方块合并游戏并冲击目标数字。",
  "sudoku-generator": "生成一个可填写的数独题目，并统计填写正确情况。",
  "spin-wheel-picker": "从自定义选项里随机抽出一个结果，适合轻量选择。",
  "jpg-to-png": "直接在浏览器里把 JPG 图片转换成 PNG。",
  "image-to-base64": "把上传的图片即时转换为 Base64 data URL。",
  "base64-to-image": "把 Base64 图片字符串解码并在浏览器里预览。",
  "pdf-to-image": "把 PDF 页面渲染成可下载的 PNG 预览图。",
  "image-to-pdf": "把一张或多张 JPG、PNG 图片合并成可下载的 PDF。",
  "pdf-merge-tool": "按顺序把多个 PDF 合并成一个 PDF 文件。",
  "pdf-split-tool": "按页码范围拆分 PDF，或按单页分别导出。",
  "pdf-compress-tool": "对 PDF 做一次轻量浏览器端结构优化并比较体积变化。",
  "file-size-converter": "在字节、KB、MB、GB、TB 之间换算文件大小。",
  "unit-converter-bytes": "把原始字节值换算成十进制和二进制存储单位。",
};

function basePhraseFromSlug(slug: string) {
  return slug.replace(/-/g, " ");
}

export function getToolSummary(slug: string, category: ToolCategoryKey, locale: SummaryLocale = "en") {
  const overrides = locale === "zh" ? SUMMARY_OVERRIDES_ZH : SUMMARY_OVERRIDES_EN;
  if (overrides[slug]) {
    return overrides[slug];
  }

  const phrase = basePhraseFromSlug(slug);

  if (locale === "zh") {
    if (slug.includes("converter")) return `在 ${phrase.replace(" converter", "")} 相关格式之间快速转换。`;
    if (slug.includes("calculator")) return `快速计算 ${phrase.replace(" calculator", "")} 相关结果。`;
    if (slug.includes("generator")) return `快速生成 ${phrase.replace(" generator", "")} 内容。`;
    if (slug.includes("validator")) return `校验 ${phrase.replace(" validator", "")} 是否有效。`;
    if (slug.includes("checker")) return `检查 ${phrase.replace(" checker", "")} 的状态、格式或有效性。`;
    if (slug.includes("decoder")) return `解析并查看 ${phrase.replace(" decoder", "")} 的可读内容。`;
    if (slug.includes("encoder")) return `对 ${phrase.replace(" encoder", "")} 进行编码处理。`;
    if (slug.includes("formatter")) return `整理并格式化 ${phrase.replace(" formatter", "")} 内容。`;
    if (slug.includes("minifier")) return `压缩并精简 ${phrase.replace(" minifier", "")} 内容。`;
    if (slug.includes("parser")) return `解析 ${phrase.replace(" parser", "")} 输入并提取结构化结果。`;
    if (slug.includes("tester")) return `测试 ${phrase.replace(" tester", "")} 行为和匹配结果。`;
    if (slug.includes("viewer")) return `查看 ${phrase.replace(" viewer", "")} 的详细内容。`;
    if (slug.includes("builder")) return `构建 ${phrase.replace(" builder", "")} 所需内容。`;
    if (slug.includes("analyzer")) return `分析 ${phrase.replace(" analyzer", "")} 并输出关键结果。`;
    if (slug.includes("estimator")) return `估算 ${phrase.replace(" estimator", "")} 相关数值。`;
    if (slug.includes("simulator")) return `模拟 ${phrase.replace(" simulator", "")} 的随机或交互结果。`;
    return `用于处理 ${phrase} 的实用工具。`;
  }

  if (slug.includes("converter")) return `Convert between ${phrase.replace(" converter", "")} formats quickly.`;
  if (slug.includes("calculator")) return `Calculate ${phrase.replace(" calculator", "")} results instantly.`;
  if (slug.includes("generator")) return `Generate ${phrase.replace(" generator", "")} values or content quickly.`;
  if (slug.includes("validator")) return `Validate whether ${phrase.replace(" validator", "")} input is valid.`;
  if (slug.includes("checker")) return `Check ${phrase.replace(" checker", "")} status, format, or validity.`;
  if (slug.includes("decoder")) return `Decode and inspect ${phrase.replace(" decoder", "")} content.`;
  if (slug.includes("encoder")) return `Encode ${phrase.replace(" encoder", "")} input instantly.`;
  if (slug.includes("formatter")) return `Format and clean up ${phrase.replace(" formatter", "")} data.`;
  if (slug.includes("minifier")) return `Minify and compress ${phrase.replace(" minifier", "")} content.`;
  if (slug.includes("parser")) return `Parse ${phrase.replace(" parser", "")} input into structured output.`;
  if (slug.includes("tester")) return `Test ${phrase.replace(" tester", "")} behavior and matches.`;
  if (slug.includes("viewer")) return `View detailed ${phrase.replace(" viewer", "")} output.`;
  if (slug.includes("builder")) return `Build ${phrase.replace(" builder", "")} data step by step.`;
  if (slug.includes("analyzer")) return `Analyze ${phrase.replace(" analyzer", "")} and inspect key results.`;
  if (slug.includes("estimator")) return `Estimate ${phrase.replace(" estimator", "")} values quickly.`;
  if (slug.includes("simulator")) return `Simulate ${phrase.replace(" simulator", "")} results instantly.`;

  const categoryFallback: Record<ToolCategoryKey, string> = {
    "date-time": `Handle ${phrase} tasks for timestamps, dates, and time math.`,
    dev: `Work with ${phrase} for developer-focused data and text workflows.`,
    finance: `Use ${phrase} for common finance and percentage calculations.`,
    web3: `Inspect or transform ${phrase} for blockchain and on-chain workflows.`,
    mini: `Use ${phrase} as a lightweight interactive browser utility.`,
    "image-file": `Process ${phrase} for common image and file tasks.`,
    ai: `Use ${phrase} to format or inspect AI-related text inputs.`,
  };

  return categoryFallback[category];
}

function buildTools(category: ToolCategoryKey, slugs: string[]): ToolDefinition[] {
  const readyTools = new Set([
    "timestamp-converter",
    "current-timestamp",
    "timestamp-milliseconds-converter",
    "date-difference-calculator",
    "time-difference-calculator",
    "add-time-to-date",
    "subtract-time-from-date",
    "business-days-calculator",
    "working-days-exclude-weekends",
    "age-calculator-exact",
    "countdown-timer-date",
    "timezone-converter",
    "timezone-difference-calculator",
    "date-to-week-number",
    "date-format-converter",
    "date-string-parser",
    "time-duration-calculator",
    "day-of-year-calculator",
    "leap-year-checker",
    "json-formatter",
    "json-minifier",
    "json-validator",
    "json-escape-unescape",
    "base64-encode-decode",
    "binary-to-text",
    "text-to-binary",
    "url-encode-decode",
    "uuid-generator",
    "word-character-counter",
    "text-case-converter",
    "slug-generator",
    "duplicate-line-remover",
    "line-sorter",
    "random-string-generator",
    "unicode-converter",
    "text-diff-checker",
    "regex-tester",
    "regex-replace-tool",
    "hash-generator-md5-sha256",
    "hex-to-string-converter",
    "string-to-hex-converter",
    "jwt-decoder",
    "json-flatten-tool",
    "json-diff-viewer",
    "json-to-csv-converter",
    "csv-to-json-converter",
    "xml-to-json-converter",
    "yaml-to-json-converter",
    "percentage-calculator",
    "discount-calculator",
    "profit-loss-calculator",
    "roi-calculator",
    "compound-interest-calculator",
    "dca-investment-calculator",
    "simple-interest-calculator",
    "loan-payment-calculator",
    "mortgage-calculator",
    "stock-average-price-calculator",
    "tax-calculator",
    "vat-calculator",
    "currency-converter",
    "exchange-rate-history-viewer",
    "inflation-calculator",
    "savings-growth-calculator",
    "net-profit-margin-calculator",
    "break-even-calculator",
    "evm-address-checker",
    "evm-checksum-converter",
    "token-decimals-converter",
    "wei-eth-converter",
    "gas-fee-calculator",
    "transaction-decoder",
    "calldata-decoder",
    "event-log-decoder",
    "abi-encode-tool",
    "abi-decode-tool",
    "keccak256-hash-generator",
    "signature-verifier",
    "recover-address-from-signature",
    "nonce-checker",
    "contract-bytecode-analyzer",
    "btc-address-generator",
    "btc-address-validator",
    "batch-btc-address-generator",
    "btc-transaction-decoder",
    "btc-raw-transaction-parser",
    "btc-fee-calculator",
    "btc-fee-estimator",
    "btc-satoshi-converter",
    "btc-script-decoder",
    "btc-transaction-size-calculator",
    "btc-change-output-calculator",
    "btc-dust-limit-calculator",
    "btc-locktime-calculator",
    "btc-weight-calculator",
    "psbt-builder",
    "psbt-decoder",
    "psbt-analyzer",
    "ordinal-inscription-builder",
    "ordinal-fee-estimator",
    "ordinal-size-calculator",
    "transaction-analyzer",
    "multi-chain-tx-viewer",
    "price-impact-calculator",
    "slippage-calculator",
    "arbitrage-profit-calculator",
    "oracle-delay-analyzer",
    "gas-optimization-analyzer",
    "liquidation-risk-calculator",
    "prompt-formatter",
    "prompt-template-generator",
    "text-to-markdown",
    "markdown-preview",
    "json-to-prompt",
    "code-explainer-lite",
    "text-summarizer-lite",
    "keyword-extractor",
    "ai-token-estimator",
    "chat-format-converter",
    "random-decision-maker",
    "random-number-generator",
    "random-password-generator",
    "random-color-generator",
    "random-gradient-generator",
    "coin-flip-simulator",
    "dice-roll-simulator",
    "number-guessing-game",
    "click-speed-test",
    "reaction-time-test",
    "typing-speed-test",
    "memory-game",
    "2048-game",
    "sudoku-generator",
    "spin-wheel-picker",
    "jpg-to-png",
    "png-to-jpg",
    "image-format-converter",
    "image-resize-tool",
    "image-compress-tool",
    "image-crop-tool",
    "image-to-base64",
    "base64-to-image",
    "pdf-to-image",
    "image-to-pdf",
    "pdf-merge-tool",
    "pdf-split-tool",
    "pdf-compress-tool",
    "file-size-converter",
    "unit-converter-bytes",
  ]);

  return slugs.map((slug) => ({
    slug,
    name: titleFromSlug(slug),
    summary: getToolSummary(slug, category, "en"),
    category,
    targetKeyword: titleFromSlug(slug).toLowerCase(),
    status: readyTools.has(slug) ? "ready" : "planned",
  }));
}

export const toolCategories = CATEGORY_META;

export const tools: ToolDefinition[] = [
  ...buildTools("date-time", [
    "timestamp-converter",
    "current-timestamp",
    "timestamp-milliseconds-converter",
    "date-difference-calculator",
    "time-difference-calculator",
    "add-time-to-date",
    "subtract-time-from-date",
    "business-days-calculator",
    "working-days-exclude-weekends",
    "age-calculator-exact",
    "countdown-timer-date",
    "timezone-converter",
    "timezone-difference-calculator",
    "date-to-week-number",
    "day-of-year-calculator",
    "leap-year-checker",
    "date-format-converter",
    "date-string-parser",
    "time-duration-calculator",
  ]),
  ...buildTools("dev", [
    "json-formatter",
    "json-minifier",
    "json-validator",
    "json-escape-unescape",
    "json-to-csv-converter",
    "csv-to-json-converter",
    "xml-to-json-converter",
    "yaml-to-json-converter",
    "json-diff-viewer",
    "json-flatten-tool",
    "base64-encode-decode",
    "url-encode-decode",
    "jwt-decoder",
    "hash-generator-md5-sha256",
    "hex-to-string-converter",
    "string-to-hex-converter",
    "binary-to-text",
    "text-to-binary",
    "unicode-converter",
    "text-diff-checker",
    "word-character-counter",
    "text-case-converter",
    "slug-generator",
    "duplicate-line-remover",
    "line-sorter",
    "regex-tester",
    "regex-replace-tool",
    "random-string-generator",
    "uuid-generator",
  ]),
  ...buildTools("finance", [
    "compound-interest-calculator",
    "simple-interest-calculator",
    "loan-payment-calculator",
    "mortgage-calculator",
    "roi-calculator",
    "dca-investment-calculator",
    "stock-average-price-calculator",
    "profit-loss-calculator",
    "percentage-calculator",
    "discount-calculator",
    "tax-calculator",
    "vat-calculator",
    "currency-converter",
    "exchange-rate-history-viewer",
    "inflation-calculator",
    "savings-growth-calculator",
    "net-profit-margin-calculator",
    "break-even-calculator",
  ]),
  ...buildTools("web3", [
    "evm-address-checker",
    "evm-checksum-converter",
    "token-decimals-converter",
    "wei-eth-converter",
    "gas-fee-calculator",
    "transaction-decoder",
    "calldata-decoder",
    "event-log-decoder",
    "abi-encode-tool",
    "abi-decode-tool",
    "keccak256-hash-generator",
    "signature-verifier",
    "recover-address-from-signature",
    "nonce-checker",
    "contract-bytecode-analyzer",
    "btc-address-generator",
    "btc-address-validator",
    "batch-btc-address-generator",
    "btc-transaction-decoder",
    "btc-raw-transaction-parser",
    "btc-fee-calculator",
    "btc-fee-estimator",
    "btc-satoshi-converter",
    "btc-script-decoder",
    "btc-transaction-size-calculator",
    "btc-change-output-calculator",
    "btc-dust-limit-calculator",
    "btc-locktime-calculator",
    "btc-weight-calculator",
    "psbt-builder",
    "psbt-decoder",
    "psbt-analyzer",
    "ordinal-inscription-builder",
    "ordinal-fee-estimator",
    "ordinal-size-calculator",
    "transaction-analyzer",
    "multi-chain-tx-viewer",
    "price-impact-calculator",
    "slippage-calculator",
    "arbitrage-profit-calculator",
    "oracle-delay-analyzer",
    "gas-optimization-analyzer",
    "liquidation-risk-calculator",
  ]),
  ...buildTools("mini", [
    "typing-speed-test",
    "click-speed-test",
    "reaction-time-test",
    "number-guessing-game",
    "coin-flip-simulator",
    "dice-roll-simulator",
    "memory-game",
    "2048-game",
    "sudoku-generator",
    "random-decision-maker",
    "random-number-generator",
    "random-password-generator",
    "random-color-generator",
    "random-gradient-generator",
    "spin-wheel-picker",
  ]),
  ...buildTools("image-file", [
    "image-resize-tool",
    "image-compress-tool",
    "image-crop-tool",
    "image-format-converter",
    "jpg-to-png",
    "png-to-jpg",
    "image-to-base64",
    "base64-to-image",
    "pdf-to-image",
    "image-to-pdf",
    "pdf-merge-tool",
    "pdf-split-tool",
    "pdf-compress-tool",
    "file-size-converter",
    "unit-converter-bytes",
  ]),
  ...buildTools("ai", [
    "prompt-formatter",
    "prompt-template-generator",
    "text-to-markdown",
    "markdown-preview",
    "json-to-prompt",
    "code-explainer-lite",
    "text-summarizer-lite",
    "keyword-extractor",
    "ai-token-estimator",
    "chat-format-converter",
  ]),
];

export function getToolBySlug(slug: string) {
  return tools.find((tool) => tool.slug === slug) ?? null;
}

export function getToolsByCategory(category: ToolCategoryKey) {
  return tools.filter((tool) => tool.category === category);
}

export function getRelatedTools(slug: string, limit = 5) {
  const tool = getToolBySlug(slug);
  if (!tool) return [];

  const sameCategory = tools.filter((item) => item.category === tool.category && item.slug !== slug);
  return sameCategory.slice(0, limit);
}

export function getCollectionStats() {
  return toolCategories.map((category) => ({
    ...category,
    count: getToolsByCategory(category.key).length,
  }));
}
